services:
  frontend:
    container_name: simple-task-management-frontend-dev
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - simple-task-management-network

  backend:
    container_name: simple-task-management-backend-dev
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: always
    depends_on:
      - database
    networks:
      - simple-task-management-network

  database:
    container_name: mongo-db-dev
    image: mongo:7.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    volumes:
      - /home/ahmad/simple-task-management-db-backup:/data/db
    networks:
      - simple-task-management-network

networks:
  simple-task-management-network:
    driver: bridge
